version: '3'

networks:
  kniffelbridge:
    driver: bridge

services:
  kniffel-java:
    build:
      context: "java"
      dockerfile: "Dockerfile"
    image: "kniffel-java"
    container_name: "kniffel-java-container"
    networks:
      - kniffelbridge

  kniffel-angular:
    build:
      context: "angular"
      dockerfile: "Dockerfile"
    image: "kniffel-angular"
    container_name: "kniffel-angular-container"
    networks:
      - kniffelbridge
    depends_on:
      - kniffel-java

  kniffel-reverse-proxy:
    build:
      context: "reverse-proxy"
      dockerfile: "Dockerfile"
    image: "kniffel-reverse-proxy"
    container_name: "kniffel-reverse-proxy-container"
    networks:
      - kniffelbridge
    ports:
      - "8083:80"
    depends_on:
      - kniffel-java
      - kniffel-angular
